import { atom } from "recoil";

export const chatListsState = atom({
  key: 'chatLists',
  default: [
    {name: 'user1', id: 0, dialog: [
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'user1'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'texttexttexttexttexttexttexttexttext'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Zonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Monie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'Tonie',  text: 'text'},
      {id: '01', avatarka: 'ava', user: 'zonie',  text: 'text'},
    ]},
    {name: 'user2', id: 1, dialog: [{id: '01', avatarka: 'ava', user: 'Monie',  text: 'user2'}]},
    {name: 'user3', id: 2, dialog: [{id: '01', avatarka: 'ava', user: 'Monie',  text: 'user3'}]},
    {name: 'user4', id: 3, dialog: [{id: '01', avatarka: 'ava', user: 'Monie',  text: 'user4'}]},
    {name: 'user5', id: 4, dialog: [{id: '01', avatarka: 'ava', user: 'Monie',  text: 'user5'}]},
    {name: 'user6', id: 5, dialog: [{id: '01', avatarka: 'ava', user: 'Monie',  text: 'user6'}]},
  ],
});